// This is just some sample data so you don't have to think of your own!
const recipes = {
//   recipe1: {
//     name: "Chicken Alfredo",
//     image: "./public/images/Homemade-Chicken-Fettuccine-Alfredo-10.jpg",
//     instructions: "1.) Bring a large pot of water to a boil, and salt generously. Add the pasta and cook according to package directions until al dente (tender but still slightly firm). Drain and toss with a splash of oil. 2.) Meanwhile, slice the chicken into 1/4-inch-thick strips, and lay them on a plate or a sheet of waxed paper. Season with salt and pepper. 3.) Heat a large skillet over medium heat. Add 2 tablespoons of the butter. When the butter melts, raise the heat to medium-high and add the chicken in 1 layer. Cook, without moving the pieces, until the underside has browned, 1 to 2 minutes. Flip the pieces, and cook until browned and cooked through, 2 to 3 minutes more. Transfer the chicken to a medium bowl. 4.) Reduce the heat to medium. Add the remaining 6 tablespoons butter. Scrape the bottom of the skillet with a wooden spoon to release any browned bits. When the butter has mostly melted, whisk in the cream and nutmeg and bring to a simmer, then cook for 2 minutes. Lower the heat to keep the sauce just warm. 5.) Whisk the Parmigiano-Reggiano into the sauce. Add the chicken and cooked pasta and toss well. Season with salt and pepper. Serve hot in heated bowls.",
//     ingredients: "Kosher salt and freshly ground black pepper - 12 ounces fettuccine - Olive oil, for tossing - 12 ounces boneless, skinless chicken breast (about 2) - 1 stick (8 tablespoons) unsalted butter - 2 cups heavy cream - 2 pinches freshly grated nutmeg - 1 1/2 cups freshly grated Parmigiano-Reggiano"
//   },
//   recipe2: {
//     name: "Garlic Butter Baked Salmon",
//     image: "./public/images/Sheet-Pan-Salmon-1.jpg",
//     instructions: "1.) Heat oven to 400°F | 200°C. On a large rimmed baking sheet, toss together potatoes with the oil, 1/2 tablespoon of garlic, 1/2 teaspoon salt, and 1/4 teaspoon pepper. Spread out in an even layer and roast for 15 minutes until they're just starting to soften and brown. 2.) Push potatoes to one side of the sheet pan and arrange salmon down the centre. Rub salmon evenly with 1 1/2 tablespoons of the minced garlic and 2 tablespoons of parsley. Add the asparagus to the other side of the pan. 3.) Combine 1/4 cup of lemon juice and 1/4 cup of the melted butter together and pour the mixture over the salmon and asparagus. Season everything with the remaining salt and pepper. 4.) Return to oven and continue baking until the potatoes are golden and fork-tender and the salmon is opaque throughout, (about 10 minutes). Optional: broil in the last 2 minutes for charred edges. 5.) Meanwhile, in a small bowl, combine the remaining butter, garlic and lemon juice with the wine (or chicken stock). Serve with the salmon, veggies and lemon slices!",
//     ingredients: "1 pound (500 g) fingerling potatoes, halved (or Yukon golds or halved white/red baby potatoes) - 2 tablespoons olive oil - 1 1/2 teaspoons salt, divided - 1/2 teaspoon cracked black pepper, divided - 4 (6 oz | 170 g) skinless salmon fillets - 2 1/2 tablespoons minced garlic, divided - 2 tablespoons fresh chopped parsley - 1/3 cup freshly squeezed lemon juice - 1/2 cup melted unsalted butter - 3 bunches asparagus, (18 spears, woody ends removed) - 2 tablespoons dry white wine (substitute with 1/4 cup low-sodium chicken broth) - 1 lemon sliced to garnish"
//   },
  recipe3: {
    name: "Chicken Alfredo",
    image: "./public/images/Homemade-Chicken-Fettuccine-Alfredo-10.jpg",
    instructions: "1.) Bring a large pot of water to a boil, and salt generously. Add the pasta and cook according to package directions until al dente (tender but still slightly firm). Drain and toss with a splash of oil. 2.) Meanwhile, slice the chicken into 1/4-inch-thick strips, and lay them on a plate or a sheet of waxed paper. Season with salt and pepper. 3.) Heat a large skillet over medium heat. Add 2 tablespoons of the butter. When the butter melts, raise the heat to medium-high and add the chicken in 1 layer. Cook, without moving the pieces, until the underside has browned, 1 to 2 minutes. Flip the pieces, and cook until browned and cooked through, 2 to 3 minutes more. Transfer the chicken to a medium bowl. 4.) Reduce the heat to medium. Add the remaining 6 tablespoons butter. Scrape the bottom of the skillet with a wooden spoon to release any browned bits. When the butter has mostly melted, whisk in the cream and nutmeg and bring to a simmer, then cook for 2 minutes. Lower the heat to keep the sauce just warm. 5.) Whisk the Parmigiano-Reggiano into the sauce. Add the chicken and cooked pasta and toss well. Season with salt and pepper. Serve hot in heated bowls.",
    ingredients: ["Kosher salt and freshly ground black pepper", "12 ounces fettuccine, Olive oil for tossing", "12 ounces boneless skinless chicken breast (about 2)", "1 stick (8 tablespoons) unsalted butter", "2 cups heavy cream", "2 pinches freshly grated nutmeg", "1 1/2 cups freshly grated Parmigiano-Reggiano"]
  }
};

export default recipes;
